### ISSUE TITLE
Selecting King's Lynn as a region HTML-quotes the apostrophe character

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/ukhpi#19]
Steps to reproduce:

* open change selections dialogue
* select the local authorities tab
* enter search term kings
* select `King's Lynn and West Norfolk`
* graph titles show `Average price: King&#39;s Lynn and West Norfolk`

**Comment by ijdickinson** [comment]
Tagging @marklunn @lrmrthomas

**Comment by ijdickinson** [comment]
Fix deployed

**Comment by lrmrthomas** [comment]
@ijdickinson  Checked this and can confirm that the graph title now displays correctly as King's Lynn and West Norfolk but the top header is still displaying incorrectly.....

'Showing index data for King&#39;s Lynn and West Norfolk, from 2015-06-01, to 2016-06-01'

**Comment by ijdickinson** [comment]
Additional fix deployed

**Comment by marklunn** [comment]
Just had a look at this and when I type 'kings' then it is not displayed.  If I type 'king's' then it is displayed.  Is there a way to allow this to be searched without typing the apostrophe?  As I doubt users would type the apostrophe when searching.

The headers are displaying correctly now though.

**Comment by marklunn** [comment]
@ijdickinson Is there any way of allowing King's Lynn to appear in the search without typing the apostrophe?  As it still doesn't show up when I type 'kings'

**Comment by ijdickinson** [comment]
I've changed the code to make matching smarter

**Comment by marklunn** [comment]
King's Lynn now shows in the search without typing the apostrophe, happy to close
